### Live tests
@base_live= https://llm.testing.waldur.com/

### Streaming (SSE)
POST {{base_live}}/api/lc/chat/stream
Accept: text/event-stream
Cache-Control: no-cache
Content-Type: application/json

{"input":"Explain RAG in one sentence."}


### Non-stream
POST {{base_live}}/api/lc/chat/invoke
Content-Type: application/json

{"input":"Explain RAG in one sentence."}
###


GET {{base_live}}/api/health