name: Build and Push Images to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'backend/')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          docker build --no-cache -f deploy/images/Containerfile.backend -t backend:latest ./backend
          docker tag backend:latest ${{ env.BACKEND_IMAGE }}
          docker push ${{ env.BACKEND_IMAGE }}

  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'frontend/')
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          docker build --no-cache -f deploy/images/Containerfile.frontend -t frontend:latest ./frontend
          docker tag frontend:latest ${{ env.FRONTEND_IMAGE }}
          docker push ${{ env.FRONTEND_IMAGE }}
