name: Build and Push Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
         filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  build-backend:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.backend == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          docker build --no-cache -f deploy/images/Containerfile.backend -t backend:latest ./backend
          docker tag backend:latest ${{ env.BACKEND_IMAGE }}
          docker push ${{ env.BACKEND_IMAGE }}

  build-frontend:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: |
          docker build --no-cache -f deploy/images/Containerfile.frontend -t frontend:latest ./frontend
          docker tag frontend:latest ${{ env.FRONTEND_IMAGE }}
          docker push ${{ env.FRONTEND_IMAGE }}