name: Build and Push Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  build-backend:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.backend == 'true'
    env:
      BACKEND_IMAGE: ghcr.io/jaxhend/llm-for-waldur/backend
      CACHE_DIR: /tmp/.buildx-cache-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Restore Docker build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: backend-build-cache-${{ github.sha }}
          restore-keys: backend-build-cache-

      - name: Build and Push Backend
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker buildx build \
            --builder ${{ steps.buildx.outputs.name }} \
            --cache-from=type=local,src=${CACHE_DIR} \
            --cache-to=type=local,dest=${CACHE_DIR}-new,mode=max \
            -f deploy/images/Containerfile.backend \
            -t $BACKEND_IMAGE:latest \
            -t $BACKEND_IMAGE:$IMAGE_TAG \
            --push \
            .
          mv ${CACHE_DIR}-new ${CACHE_DIR}

  build-frontend:
    runs-on: ubuntu-latest
    needs: filter
    if: needs.filter.outputs.frontend == 'true'
    env:
      FRONTEND_IMAGE: ghcr.io/jaxhend/llm-for-waldur/frontend
      CACHE_DIR: /tmp/.buildx-cache-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Restore Docker build cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: frontend-build-cache-${{ github.sha }}
          restore-keys: frontend-build-cache-

      - name: Build and Push Frontend
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker buildx build \
            --builder ${{ steps.buildx.outputs.name }} \
            --cache-from=type=local,src=${CACHE_DIR} \
            --cache-to=type=local,dest=${CACHE_DIR}-new,mode=max \
            -f deploy/images/Containerfile.frontend \
            -t $FRONTEND_IMAGE:latest \
            -t $FRONTEND_IMAGE:$IMAGE_TAG \
            --push \
            .
          mv ${CACHE_DIR}-new ${CACHE_DIR}
